[package]
name = "bet"
type = "contract"
authors = [ "" ]
compiler_version = ">=0.25.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "aztec-packages-v0.52.0", directory = "noir-projects/aztec-nr/aztec" }
authwit = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "aztec-packages-v0.52.0", directory = "noir-projects/aztec-nr/authwit" }
token = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "aztec-packages-v0.52.0", directory = "noir-projects/noir-contracts/contracts/token_contract" }
